"""Type stubs for TensorFlow Lite runtime"""

class Interpreter:
    def __init__(self, model_path: str): ...
    def allocate_tensors(self) -> None: ...
    def get_input_details(self) -> list: ...
    def get_output_details(self) -> list: ...
    def set_tensor(self, index: int, value) -> None: ...
    def invoke(self) -> None: ...
    def get_tensor(self, index: int): ...
