"""Type stubs for OpenCV"""

import numpy as np

def resize(src: np.ndarray, dsize: tuple[int, int]) -> np.ndarray: ...
def cvtColor(src: np.ndarray, code: int) -> np.ndarray: ...
def GaussianBlur(src: np.ndarray, ksize: tuple[int, int], sigmaX: float) -> np.ndarray: ...
def Canny(image: np.ndarray, threshold1: float, threshold2: float) -> np.ndarray: ...
def findContours(image: np.ndarray, mode: int, method: int) -> tuple: ...
def contourArea(contour: np.ndarray) -> float: ...
def arcLength(curve: np.ndarray, closed: bool) -> float: ...
def approxPolyDP(curve: np.ndarray, epsilon: float, closed: bool) -> np.ndarray: ...
def rectangle(img: np.ndarray, pt1: tuple[int, int], pt2: tuple[int, int], color: tuple, thickness: int) -> None: ...
def circle(img: np.ndarray, center: tuple[int, int], radius: int, color: tuple, thickness: int) -> None: ...
def putText(img: np.ndarray, text: str, org: tuple[int, int], fontFace: int, fontScale: float, color: tuple, thickness: int) -> None: ...

COLOR_RGB2GRAY: int
RETR_EXTERNAL: int
CHAIN_APPROX_SIMPLE: int
FONT_HERSHEY_SIMPLEX: int
