"""Type stubs for picamera2"""

import numpy as np

class Picamera2:
    def __init__(self): ...
    def create_preview_configuration(self, main: dict) -> dict: ...
    def configure(self, config: dict) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def capture_array(self) -> np.ndarray: ...
