"""Type stubs for pyserial"""

class Serial:
    def __init__(self, port: str, baudrate: int, timeout: float = 1): ...
    def write(self, data: bytes) -> int: ...
    def read(self, size: int) -> bytes: ...
    @property
    def in_waiting(self) -> int: ...
    @property
    def is_open(self) -> bool: ...
    def close(self) -> None: ...
